### ISSUE TITLE
See if there is a way of plotting the ontology associated with a cell type, e.g. show all nodes that are significantly enriched, and the relationship between them

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/rare_disease_celltyping#10]
This would be good if we wanted to build a website showing the results associated with each cell type

Try using this package: https://cran.r-project.org/web/packages/ontologyPlot/vignettes/plotting-ontological-terms.html

**Comment by bschilder** [comment]
This is now the Cell Select app:
https://neurogenomics.shinyapps.io/cell_select/
