### ISSUE TITLE
Work with Alan Murphy to move `RunEWCE` and `EWCEWrapper` into the main EWCE package

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/rare_disease_celltyping#16]
Currently they are within https://github.com/neurogenomics/rare_disease_ewce/blob/master/TabulaMuris_Results/Results-Generation-100000-MC-WithSaving.R

**Comment by bschilder** [comment]
I'm not exactly sure what these wrapper functions are named now, but I think it should be ok to simply have them be part of MultEWCE since it's diverged quite a bit from EWCE.
