### ISSUE TITLE
There's a list of ~400 phenotypes that didn't run succesfully. Bobby thinks it's because of e.g. hyphens in the name. Need to figure out why this was and get them working.

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/rare_disease_celltyping#20]
@ovrhuman can you upload the list here

**Comment by bschilder** [comment]
Think this was done and added to "[Descartes_All_Results_extras.rda](https://github.com/neurogenomics/rare_disease_celltyping/blob/master/results/Descartes_All_Results_extras.rda)"
https://github.com/neurogenomics/rare_disease_celltyping/tree/master/results
