### ISSUE TITLE
Setup the document so that the text can be edited in authorea + figures regenerated from a markdown file

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/rare_disease_celltyping#23]
Basic idea for this is described here:
https://www.authorea.com/users/2191/articles/278550-a-step-by-step-guide-to-using-authorea-github-and-jupyter-for-reproducible-dynamic-collaborative-data-science-in-public-health

This is the best guide for how it can be done that I've seen:
https://21docs.com/users/244977/articles/324602-how-to-combine-r-with-authorea-to-collaboratively-write-reproducible-scientific-papers

Authorea allows collaborative editing of the markdown document + references

Authorea documents can be linked to a github repo

Then we keep a markdown document within the same repo. This is used to (re)generate all the figures as required. The markdown document probably wouldn't perform the whole (computationally intensive) analysis, it would be for e.g. generating figures. The figures are then saved as *.jpeg and read into the Authorea document.

**Comment by bschilder** [comment]
Done by @bobGSmith in Rmarkdown for his thesis:
https://github.com/neurogenomics/rare_disease_celltyping/blob/master/old/reports/paper.rmd
