### ISSUE TITLE
Graphs showing relationship between celltype enrichment strengths + ontology level, should use violin plots

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/rare_disease_celltyping#24]
![image](https://user-images.githubusercontent.com/33265555/130612838-a6c82a96-7c06-433a-abd5-fc1e1a00c9e3.png)

Currently these just show the mean value. Would be better to show the distribution at each level with violin plots.

**Comment by bschilder** [comment]
Done in Fig 2:
https://github.com/neurogenomics/rare_disease_celltyping/blob/master/figures/manuscript_figures_july_2022.pdf
