### ISSUE TITLE
Cleanly separate functions from scripts + ensure all functions pass dev::check()

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/rare_disease_celltyping#36]
At the moment some function files have scripts at the top: remove this code, and have a master script/markdown file which calls functions. E.g.

**Comment by bschilder** [comment]
Packages now passing CRAN and Bioc checks here:
https://github.com/neurogenomics/HPOExplorer
https://github.com/neurogenomics/MultiEWCE
