### ISSUE TITLE
Group plots into larger figures

### ISSUE THREAD

**Issue by bobGSmith** [neurogenomics/rare_disease_celltyping#39]
What do you think of the rough grouping i have here, and what ones should i exclude? 

https://github.com/neurogenomics/rare_disease_ewce/blob/master/figure_group_planning.md

@NathanSkene @bschilder

**Comment by bschilder** [comment]
This is now merged in Fig 1:
https://github.com/neurogenomics/rare_disease_celltyping/blob/master/figures/manuscript_figures_july_2022.pdf
