### ISSUE TITLE
Cut the words in the paper back to 2500 to fit with requirements for science report submission

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/rare_disease_celltyping#40]
Here's the word limit info: https://www.science.org/content/page/science-information-authors

Reports (up to ~2500 words including references, notes and captions–corresponds to ~3 printed pages in the journal) present important new research results of broad significance. Reports should include an abstract, an introductory paragraph, up to four figures or tables, and about 30 references. Materials and Methods should be included in supplementary materials, which should also include information needed to support the paper's conclusions.

**Comment by bschilder** [comment]
Decided to go with Nat Comm for the longer format, so we dont have these same constraints anymore.
This was especially necessary after adding @momokootani 's work
