### ISSUE TITLE
For the recurrent infection plots, set scale_y=free

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/rare_disease_celltyping#43]
![image](https://user-images.githubusercontent.com/33265555/146397169-7e95e4c9-a634-44aa-ae8c-3d36376ca8e7.png)

It will help shrink the figure smaller

**Comment by bschilder** [comment]
I actually think the version with the shared y-scales is ok, and it makes it easier to compare across plots:
https://github.com/neurogenomics/rare_disease_celltyping/blob/master/figures/manuscript_figures_july_2022.pdf

@NathanSkene @KittyMurphy, thoughts?
