### ISSUE TITLE
In Fig 3a,b,c, remove the "other" line... it isn't required and isn't really in contrast to the phenotypes

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/rare_disease_celltyping#44]
![image](https://user-images.githubusercontent.com/33265555/172393220-e3523e84-4cad-4d2f-bfff-b7824cb54b0a.png)

**Comment by bschilder** [comment]
Done in Fig 1:
https://github.com/neurogenomics/rare_disease_celltyping/blob/master/figures/manuscript_figures_july_2022.pdf
