### ISSUE TITLE
Are congenital phenotypes more enriched for fetal cell types?

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/rare_disease_celltyping#47]
- Are congenital phenotypes are more strongly enriched for fetal cell types than congenital phenotypes?
  - **Strategy**: Identify cell types that only occur in fetal samples (and not adult samples)
- Are congenital phenotypes are more strongly enriched for fetal cell types vs. adult cell types?
  - **Strategy**: Identify cell types that occur in both fetal and adult samples, and compare their relative enrichment levels in congenital vs. non-congenital disease.

We can assess these questions with the [Human Cell Landscape](https://www.nature.com/articles/s41586-020-2157-4#data-availability) as it contains both fetal and adult cell types. 

We can use the "congenital_onset" column from  GPT annotations to categorise each phenotype.
https://github.com/neurogenomics/RareDiseasePrioritisation/issues/19

**Comment by bschilder** [comment]
Report here:
https://neurogenomics.github.io/rare_disease_celltyping/code/congenital

To do:
- [ ] Reread the HCL paper and check how they annotated their cell types
- [ ] Check my code for processing the HCL scRNA-seq metadata (and thus the downstream CTD)

**Comment by bschilder** [comment]
After a couple of failed attempts to do the tests manually, i found `ggstatsplot::ggbarstats` which makes exactly what I wanted to do super easy:


```R
ggstatsplot::ggbarstats(res_gpt[q<0.05,],
                        x="fetal_celltype",
                        y="congenital_onset",
                        package="palettetown",
                        palette="mew",
                        proportion.test	= TRUE
                        ) 
```



![Image](https://github.com/neurogenomics/rare_disease_celltyping/assets/34280215/c99bb978-2865-473f-a5e6-51388fd32b0c)

It does several things, including an overall chi squared test on a contingency table of counts per group. `Xpearson` is Pearson's contingency coefficient (i.e. effect size of fetal/non-fetal celltype proportions across all 3 groups). `Vcramer` is Cramer's V, which is just another way of computing effect size. You also get 95% CIs.

In addition, it computes a series of one-sample chi squared test within each of the 3 groups, basically asking "within this group (e.g. often congenital phenotypes) does the proportion of enriched fetal vs. non-fetal celltypes differ significantly from what is expected by chance?".

**Comment by NathanSkene** [comment]
Those are some serious p-values! 😀 Great work Brian, this is a super cool result, think this counts as benchmarking genetic cell type mapping as well!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
