### ISSUE TITLE
Assess pLI in HPO genes

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/rare_disease_celltyping#50]
Originally discussed here: 
- https://github.com/neurogenomics/MultiEWCE/issues/16#issuecomment-1799340362

We should asses the relationship between HPO genes and probability of Loss Intolerance (pLI) scores.

# Questions

- [ ] Do HPO genes have greater pLI than randomly sampled background genes from the human genome?
- [ ] Is there a relationship between cell-type specificity scores (from our CTDs) and pLI?
- [ ] Do phenotypes with stronger cell type enrichment (in terms of fold-change) tend to have genes with greater pLI scores?
- [ ] Is there a relationship between pLI and [GenCC](https://thegencc.org/) evidence scores? (use `HPOExplorer::get_gencc()` to get the GenCC data)

@KittyMurphy it would be great if you could start exploring these questions and upload them as rmarkdown reports in this repo. 
Perhaps start by just uploading a script showing me how to get the pLI scores for all genes, so I can start exploring this a bit as well.

Also just came across this paper:
- https://onlinelibrary.wiley.com/doi/10.1002/humu.23763

**Comment by bschilder** [comment]
> https://onlinelibrary.wiley.com/doi/10.1002/humu.23763

Found this paper quite helpful in understanding pLI (and its many shortcomings as a metric). 

Some additional (or alternative) metrics to consider:
- [AlphaMissense](https://www.science.org/doi/10.1126/science.adg7492) predictions (aggregated per gene).
- [Variant Effect Predictor](https://useast.ensembl.org/info/docs/tools/vep/index.html)

**Comment by bschilder** [comment]
Ok, so while the data in VEO is super useful, the VEP software is a hot garbage fire that is virtually uninstallable. I tried everything under the sun:
https://gist.github.com/bschilder/8a64d266e0e3ab18075274ad539985ac
 

However, I was able to extract the AlphaMissense predictions directly! Turns out they already computed per gene scores for the entire protein-coding genome [here](https://console.cloud.google.com/storage/browser/dm_alphamissense;tab=objects?pli=1&prefix=&forceOnObjectsSortingFiltering=false) (see their README):

> AlphaMissense_gene_hg19.tsv.gz, AlphaMissense_gene_hg38.tsv.gz
Gene-level average predictions, which were computed by taking the mean
alphamissense_pathogenicity over all possible missense variants in a transcript
(canonical transcript).


With a little extra postprocessing, I got the gene symbols: 

```R
 am <- data.table::fread("https://storage.googleapis.com/dm_alphamissense/AlphaMissense_gene_hg38.tsv.gz")
  am$enst_id <- stringr::str_split(am$transcript_id,"\\.", simplify = TRUE)[,1] 
  map <- orthogene::map_genes(genes = unique(am$enst_id), 
                              target = "ENST",
                              species="human",
                              drop_na = FALSE, 
                              mthreshold = Inf)
  am_mapped <- unique(map[,c("input","name")]) |>
    data.table::data.table(key = "input") |>
    data.table::merge.data.table(am, by.x = "input", by.y = "enst_id")
am_mapped
```

![Image](https://github.com/neurogenomics/rare_disease_celltyping/assets/34280215/dc73999c-f850-46a5-a38c-fae502e2f650)

pLI is still problably worth looking at, but I think ML-based AlphaMissense metric circumvents many of the shortcomings of the rule-based pLI metric.

**Comment by bschilder** [comment]
Found the latest pLI data from gnomad as well:
https://gnomad.broadinstitute.org/downloads/#v4-constraint

Import that now for comparison with AlphaMissense.

**Comment by NathanSkene** [comment]
How would an AI model give us population frequency? I thought current generation AI models of protein folding are also really bad at predicting variant effects?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by KittyMurphy** [comment]
Just having a look into what I did previously when looking at pLI and genes under selective pressure. 

I used the pLI for human transcripts from this study: [The mutational constraint spectrum quantified from variation in 141,456 humans](https://www.nature.com/articles/s41586-020-2308-7#data-availability). 

I'm attaching the relevant supplementary table: 
[supplementary_dataset_11_full_constraint_metrics.tsv.zip](https://github.com/neurogenomics/rare_disease_celltyping/files/13449422/supplementary_dataset_11_full_constraint_metrics.tsv.zip). 

But as you've shared @bschilder,  there is a more up to date version of pLI data.

**Comment by bschilder** [comment]
> How would an AI model give us population frequency? I thought current generation AI models of protein folding are also really bad at predicting variant effects?

Are you talking about variant population frequency, phenotype frequency, or disease frequency?
In any case, none of these were the intended usage of pLI as outlined here:
https://github.com/neurogenomics/rare_disease_celltyping/issues/50#issue-1981995728

Also see here for my explanation of why pLI would not be appropriate for estimating population prevalence. Instead, getting epidemiological stats on population prevalence would make much more sense.
- https://github.com/neurogenomics/RareDiseasePrioritisation/issues/34#issuecomment-1814445527
