### ISSUE TITLE
`phenomix`: Exploring more efficient methods for celltype enrichment

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/rare_disease_celltyping#51]
@NathanSkene @KittyMurphy  @Al-Murphy 

While I was waiting for the latest phenotype-celltype enrichment results to finish running on HPC, I starting exploring whether we could run phenotype-celltype association tests in a more efficient manner. This was implemented within my package [`phenomix`](https://github.com/neurogenomics/phenomix).

Short answer: yes, I was able to run all HPO x Descartes celltype enrichment tests but orders of magnitude faster using only my laptop. 

All code to run the tests and benchmarking can be found [here](https://github.com/neurogenomics/rare_disease_celltyping/blob/master/code/phenomix.Rmd). Will generate a proper HTML report with figures as well.

# Approach
In this approach, I:
1. use the [GenCC](https://search.thegencc.org/) evidence scores for each disease-gene link-
2. merge that with the disease-phenotype-gene data in HPO
3. construct a gene x phenotype matrix (filled with the GenCC scores)
4. run regression on every combination of phenotype and celltype in the level 2 specificity matrix of the Descartes CTD (via `phenomix::iterate_lm`)
5. apply multiple-testing correction

Fundamentally, the biggest differences between `MultiEWCE` and `phenomix` are:
1. `MultiEWCE` treats it as a gene set enrichment problem, while `phenomix` treats it as a linear regression problem.
2. `MultiEWCE` uses bootstrapping (100,000 iterations per phenotype-celltype test), while `phenomix` only needs to run one rep per phenotype-celltype test.

# Speed
## `MultiEWCE`: 
- **N tests**: 6916 phenotypes x 77 celltypes (532,532 tests)
- **Time**: Completed overnight (don't have a precise estimate)
- **Resources**: 6916 array subjobs with 4 cores (27,664 cores total) and 128Gb mem per subjob
## `phenomix`:  
- **N tests**: 10,948 phenotypes x 77 celltypes (844,613 tests)
- **Time**: 30.5 min 
- **Resources**: Local Macbook Pro, paralellised across 10 cores. Only ever used a small fraction of my 64Gb of memory.

# Benchmarking. 
- I benchmarked these new results against Bobby's old `MultiEWCE` results. Will repeat once i finish the updated `MultiEWCE` tests using the fixed Descartes CTD (and the Human Cell Landscape CTD).
- In the end, there is 96.66% concordance between the top most enriched celltype (the one with the highest fold-change after filtering by q<0.05 within the `MultiEWCE` results) between `MultiEWCE` and my new method (implemented in `phenomix`).
- Will need to explore exactly how much the GenCC scores help these analyses. ie. does making the gene links binary degrade performance substantially? (1=associated with the disease/phenotype, 0=not).

# Conclusion
This new method will still require more benchmarking to ensure it's robust, and I think for the sake of the rare disease celltyping paper we should stick to our original `MultiEWCE` approach (partly for the sake of not having to rewrite it..). But wanted to document this here to let us know we have a new approach in our back pocket.

**Comment by bschilder** [comment]
@NathanSkene I compared the `phenomix` results to the `MultiEWCE` results using the Monarch KG phenotype-celltype links ground truth as a benchmark.

## `MultiEWCE`
- 17,069 significant phenotype-celltype associations @ FDR<0.05
- 2,482 phenotypes (22.5% of the 11,025 HPO terms with gene annotations) with at least one cell type association @ FDR<0.05
- 64% of Monarch KG phenotype-celltype associations recovered

## `phenomix`
- 25,809 significant phenotype-celltype associations @ FDR<0.05 (1.5x more than`MultiEWCE`)
- 7,801 phenotypes (70.1% of the 11,025 HPO terms with gene annotations) with at least one cell type association @ FDR<0.05 (3.1x more than `MultiEWCE`)
- 81% of Monarch KG phenotype-celltype associations recovered

So `phenomix` does much better than `MultiEWCE` in terms of recovering known phenotype-celltype associations and characterising a much greater proportion of the HPO phenotypes. Of course, for both these methods it remains unclear to what extent there are false positives, which is harder to assess than false negatives.

**Comment by bschilder** [comment]
I've been evaluating the performance of MultiEWCE vs. phenomix and I think I may have changed my mind. phenomix seems to be performing better across the board, based on both the Fig 1 plots (esp % on-target celltypes in FIg 1d)

Also, phenomix now recovers 90.24% of ground truth Monarch phenotype-cell type associations, while MultiEWCE only recovers 62%. Our coverage of the HPO is also much better: phenomix = 9841/11058 phenotypes (89%); MultiEWCE 2897/11058 (26%)

If phenomix were simply produced tons of spurious results I'd be hesitant to use them, but the Fig1 plots below show that this is not the case, and that performance is actually improved on average across different HPO branches.

This wouldn't require changing else in the HPOExporer/MultiEWCE pipeline, as the results format is exactly the same between phenomix/MultiEWCE.

# Fig 1

## MultiEWCE

[fig1.pdf](https://github.com/neurogenomics/rare_disease_celltyping/files/14318866/fig1.pdf)


## phenomix



[fig1_phenomix.pdf](https://github.com/neurogenomics/rare_disease_celltyping/files/14318868/fig1_phenomix.pdf)

**Comment by NathanSkene** [comment]
What is phenomix?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bschilder** [comment]
> What is phenomix? Sent from Outlook for iOS<https://aka.ms/o0ukef>
Please read the first post in this Issue:
https://github.com/neurogenomics/rare_disease_celltyping/issues/51#issue-1987374131

**Comment by bschilder** [comment]
I ran some benchmarking for the results of each method.  My metric is % recall of ground truth phenotype-cell type relationships from the Monarch knowledge graph.

One issue is that the cell types in Monarch KG and in our single-cell datasets are annotated at different levels in the Cell Ontology (eg. "neutrophil" vs, "mature neutrophil"). Therefore the question of % recall can be computed at different levels of distance in the Cell Ontology graph. So for each phenotype in the Monarch KG ground truth set, I computed the minimum number of nodes you need to travel through in the graph to get to the nearest common ancestor of any of our significantly enriched cell types for that phenotype. In cases where the target cell type is the ancestor of one of our enriched cell types, i simply counted that as a hit (at distance=0). Then i computed the % of phenotype-cell type relationships we recalled at each graph distance. 

So phenomix achieves 45% recall at a distance of 0, and up to ~90% at a distance of 10 (the performance is capped by the % of phenotype we had enrichment for in any cell type).
MultiEWCE starts at ~27% but caps out at 51%. I think my original estimate of 62% was a bit of an overestimate bc it was based on me manually going through each of the cell types, googling them, and seeing if they were somewhat related across the ground truth vs. our results for each phenotype. The method I'm describing here is much more systematic and is done entirely programmatically using the Cell Ontology graph (thus unbiased by any of my judgement calls of cell type equivalence).

![Image](https://github.com/neurogenomics/rare_disease_celltyping/assets/34280215/61afc4b9-47c5-4bc0-b561-f846ece4a9f6)
