### ISSUE TITLE
Regenerate manuscript figures with new results

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/rare_disease_celltyping#59]
# Original figures
Code for generating figures:
https://github.com/neurogenomics/rare_disease_celltyping/blob/f7701e7e9f859a947d5d83cb5c62cc3b4afaf80b/figures/manuscript_figures_july_2022.Rmd

## Fig 1
https://github.com/neurogenomics/rare_disease_celltyping/blob/f7701e7e9f859a947d5d83cb5c62cc3b4afaf80b/figures/manuscript_fig_1.pdf

## Fig 2
https://github.com/neurogenomics/rare_disease_celltyping/blob/f7701e7e9f859a947d5d83cb5c62cc3b4afaf80b/figures/manuscript_fig_2.pdf

## Fig 3  
https://github.com/neurogenomics/rare_disease_celltyping/blob/f7701e7e9f859a947d5d83cb5c62cc3b4afaf80b/figures/manuscript_fig_3.pdf

**Comment by bschilder** [comment]
# Updated figures

I've rewritten all of the code to make the main figures because the old code was mostly hard-coded and couldn't be used for the new results. The updated functions are now included within a single function in `MultiEWCE` for better reproducibility.

- All plots now include both DescartesHuman and HumanCellLandscape results.

## Fig 1

### Changes
#### Subplot a.
- The original plot assigned each cell type to a tissue, but this didn't quite make sense since many cell types can be found across multiple tissues. Instead, I turned this subplot into a summary of the total number of enriched phenotypes (including all, but not limited to, ancestors in the facets below).
#### Subplot b.
- Included extra HPO ancestor facets for the musculoskeletal and endocrine system, so we can see that the relevant cell types from those systems match well with the enrichment results.
- Previously, The x-axis cell type labels were manually annotated based on which category we thought they belong to. Instead, I've replaced with with a data-driven approach that colors each celltype by whichever HPO ancestor that celltype was most frequently enriched in (after applying a within-ancestor normalisation to account for differences in the y-axis of each facet). Readers can then decide for themselves whether our assignment meets their expected assignment (e.g. do they agree that cardiomyotes should be assigned to abnormalities of the cardiovascular system).
- Rewrote the proportional enrichment tests to compare the % enriched on-target cell types within each HPO branch relative to *all* other branches (not just the ones shown in this plot). This gives a more accurate estimate of which cell types tend to be specifically enriched in each branch. The significance of these tests results (after Bonferonni correction) are shown as asterices above each bar).
#### Subplot c.
- Created the dendrogram from the Cell Ontology graph instead of the CTD, as this plot now includes results from multiple CTD references (Descartes + HCL). Dendrogram now placed at the bottom to more easily align with the cell type names.
#### Subplot d.
- Recreated the bottom subfigure to include all cell types that fall within a given branch of the Cell Ontology, matched with a corresponding analogous branch in the HPO (e.g. Abnormalities of the cardiovascular system should be strongly enriched for all types of cardiocytes) .


```r
results <- MultiEWCE::load_example_results(multi_dataset=TRUE)
out <- MultiEWCE::plot_bar_dendro(results = results)
```
 

![Image](https://github.com/neurogenomics/rare_disease_celltyping/assets/34280215/b3bbf121-551c-415a-9704-677cada18a7f)


## Fig 2

```R
out <- MultiEWCE::plot_ontology_levels()
```

### Changes

- Ran correlations on each variable (N genes, N cell types, logFC) vs. phenotype ontology level.
- HPO levels now go deeper (12-16) bc the HPO has since been updated with more terms and bc i included the top level term ("All"). 
- Level 0 (All) is now the highest level, instead of starting at 1 like before.
- The relationship between HPO term level and logFC isn't quite as clean as [before](https://github.com/neurogenomics/rare_disease_celltyping/blob/f7701e7e9f859a947d5d83cb5c62cc3b4afaf80b/figures/manuscript_fig_2.pdf) (even after a log2 transform), but the relationship is still quite significant.
- I'm only using logFC for pheno-celltype tests in which the FDR was significant. Otherwise, logFC becomes too noisy and not that meaningful.

[figure2 copy.pdf](https://github.com/neurogenomics/rare_disease_celltyping/files/14269269/figure2.copy.pdf)



## Fig 3

## Changes

- Only showing subset "Recurrent bacterial infections" to reduce the number of facets and make the plot for more focused and legible.
- [ ] **TO DO**:  Need to add back the proportional enrichment tests here. 


![Image](https://github.com/neurogenomics/rare_disease_celltyping/assets/34280215/7aa8447c-5065-4d98-99ed-5de2b66c1aee)

**Comment by NathanSkene** [comment]
Once you’ve got captions for all the figures, can you schedule a meeting (at least an hour, probably two) to go through them all together in detail

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
