### ISSUE TITLE
Consider extending fetal vs. adult cell type analyses

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/rare_disease_celltyping#75]
![Screenshot 2024-06-15 at 16 35 09](https://github.com/neurogenomics/rare_disease_celltyping/assets/34280215/ae1e51b6-9020-412b-97d3-5e3582f53d27)

Transcribed comments from @NathanSkene :

> "Might be intending to role what percentage are only associated with the fetal cell type, vs also the adult. Would also expect this to increase from always → never." 

> "Could you calculate which phenotypes show the greatest difference in association between the fetal and adultversion of [??] celltypes? We should include this as supplementing table.
> "Include a figure showing cell type associations for 3 traits which are best examples of this with different cell types"

> "For each cell type for which we have fetal & adult, we should let it more severe phenotypes are more associated with fetal or adult, e. g. are they randomly distributed, or is bias to fetal? Then plot the most fetal /adult biased cell type."

![Screenshot 2024-06-15 at 16 40 47](https://github.com/neurogenomics/rare_disease_celltyping/assets/34280215/05599c44-6e8b-43bd-a973-330a6f1ccd89)

> "Is there something interesting  we can say about the fetal cells which are associated with these? e. g. specific examples."

**Comment by bschilder** [comment]
I'm going to focus on finishing up the manuscript and then will circle back to these questions if I have time.

**Comment by bschilder** [comment]
Revisiting these suggestions now.

**Comment by bschilder** [comment]
> "Might be intending to role what percentage are only associated with the fetal cell type, vs also the adult. Would also expect this to increase from always → never." 

This does indeed seem to be case. I identified all cell types that had both adult and fetal/embryonic versions. of those, I checked:
1.  what proportion of phenotypes were associated with the fetal/embryonic version
2.  what proportion of phenotypes were ONLY associated with the fetal/embryonic version

## Cell type exists in fetal samples
![image](https://github.com/user-attachments/assets/bdfc6a63-4630-490f-ad78-5fffe31a13d9)


## Cell type ONLY exists in fetal samples

![image](https://github.com/user-attachments/assets/63ea3b57-25c0-47c1-91e9-f320668c674a)

**Comment by bschilder** [comment]
> "Could you calculate which phenotypes show the greatest difference in association between the fetal and adultversion of [??] celltypes? We should include this as supplementing table.
> "Include a figure showing cell type associations for 3 traits which are best examples of this with different cell types"

I computed the difference in p-values between the fetal version and non-fetal version of each cell type within each phenotype. The distribution of the differences were normally distributed.

![image](https://github.com/user-attachments/assets/4d00c4f5-44db-48f2-b6e9-c786861b16d4)

Here are the top 10 phenotypes for which the difference was greatest:

![Screenshot 2024-08-16 at 15 01 12](https://github.com/user-attachments/assets/ae5edf02-175a-4677-babd-e77b0eccbd8f)

Many of these are morphological abnormalities that would arise during fetal development, which aligns with our hypothesis.

**Comment by NathanSkene** [comment]
Great! I think these really help consolidate.

Shall we include the plot for "Association exists ONLY with fetal version of cell type" as a second subplot alongside the first?

Thoughts on how to present the above table of "fetal only phenotypes" as a figure? Some ideas:
- Supplementary table with all those which are highly signif
- Calculate enrichments of biased phenotypes in higher nodes of HPO ontology, and plot the enrichment values for the most biased nodes?
- Celltypes along x-axis, showing which are most associated with fetal-only / adult-only phenotypes

**Comment by bschilder** [comment]
> "For each cell type for which we have fetal & adult, we should let it more severe phenotypes are more associated with fetal or adult, e. g. are they randomly distributed, or is bias to fetal? Then plot the most fetal /adult biased cell type."

I think what you're asking here is to plot the distribution of feta/adult cell type associations across phenotypes stratified by severity classes.

There doesn't appear to be any systematic differences across severity classes.

## Association exists with fetal version of cell type


![image](https://github.com/user-attachments/assets/1ea9bbac-9afb-4ec3-b549-83ae82db265e)

## Association exists ONLY with fetal version of cell type

![image](https://github.com/user-attachments/assets/9f7a7048-4c1c-452d-a38a-8274536ca466)

**Comment by NathanSkene** [comment]
Suprising! I'd assumed fetal cell types would cause more profound disease, but guess that knocks that idea on the head! Thanks. Have that one as supplementary and reference from text?

**Comment by bschilder** [comment]
> Great! I think these really help consolidate.
> 
> Shall we include the plot for "Association exists ONLY with fetal version of cell type" as a second subplot alongside the first?

I think it might be better to add the "Association exists ONLY with fetal version of cell type" subplot in the supplement and make reference to the result in the main text. This helps keep the main text plot simple and easier to understand.

> Thoughts on how to present the above table of "fetal only phenotypes" as a figure? Some ideas:
> 
> * Supplementary table with all those which are highly signif

By "highly signif", I assume you mean "phenotypes that are highly significantly enriched for only the fetal version OR only the adult version of a given cell type?"

> * Calculate enrichments of biased phenotypes in higher nodes of HPO ontology, and plot the enrichment values for the most biased nodes?

Did this by testing for enrichment of HPO ancestors in the top 50 (fetal cell type-biased) and bottom 50 (adult cell type-biased) phenotypes. 
Using on the top/bottom 10 phenotypes didn't yield any significant enrichments.

Could include these results as an additional supp table or plot. 

```R
gdat <- unique(results[has_adult_and_fetal==TRUE,
                           c("hpo_id","cl_id",
                             "fetal_nonfetal_pdiff",
                             "congenital_onset")][!is.na(congenital_onset) & !is.na(fetal_nonfetal_pdiff)])|>
      data.table::setorderv("fetal_nonfetal_pdiff", -1)

 dag_enrich_top <- (simona::dag_enrich_on_offsprings(dag=hpo, terms = utils::head(unique(gdat$hpo_id),50))|>
      data.table::data.table())[p_adjust<0.05]
dag_enrich_bottom <- (simona::dag_enrich_on_offsprings(dag=hpo, terms = utils::tail(unique(gdat$hpo_id),50))|>
                     data.table::data.table())[p_adjust<0.05]
```
![Screenshot 2024-08-16 at 16 44 37](https://github.com/user-attachments/assets/cb673d8f-b84d-49dd-b3c8-37d1e08d9f53)

> * Celltypes along x-axis, showing which are most associated with fetal-only / adult-only phenotypes

Because I defined the "fetal_nonfetal_pdiff" as:
```R
mean(p[fetal_celltype==FALSE], na.rm=TRUE) - mean(p[fetal_celltype==TRUE], na.rm=TRUE)
```
...I expect the most fetal cell biased phenotypes to have the largest values (closer to 1) and the most adult cell type-biased phenotypes to have the smallest values (closer to -1). 

Despite this, "primordial germ cell" seems to be appearing in the latter group. Not sure what happened there...

```R
utils::head(unique(gdat$cl_name))
utils::tail(unique(gdat$cl_name)) 
```

![Screenshot 2024-08-16 at 16 57 56](https://github.com/user-attachments/assets/c7297e00-1a3c-4b4d-83c3-3a73a3693d69)

**Comment by bschilder** [comment]
> Despite this, "primordial germ cell" seems to be appearing in the latter group. Not sure what happened there...

Decided to take a more systematic enrichment approach comparable to the HPO ancestor enrichment tests. Instead, I'm getting the most enriched Cell Ontology ancestral terms.

It's a bit hard to say what the best way to do this is (eg. number of top/bottom input cell types) but this seems to make slightly more sense?

```R
  cl <- KGExplorer::get_ontology("cl")
    cl_enrich_top <- (simona::dag_enrich_on_offsprings(
      dag=cl,
      terms = utils::head(unique(gdat$cl_id),20))|>
        data.table::data.table(key = "p_value"))[p_adjust<0.05 & depth>4]
    cl_enrich_bottom <- (simona::dag_enrich_on_offsprings(
      dag=cl,
      terms = utils::tail(unique(gdat$cl_id),20))|>
        data.table::data.table(key = "p_value"))[p_adjust<0.05 & depth>4]
```

![Screenshot 2024-08-16 at 17 18 12](https://github.com/user-attachments/assets/b665feb1-b792-4dad-885d-e52102a4616c)
![Screenshot 2024-08-16 at 17 18 23](https://github.com/user-attachments/assets/70d99609-4710-47b8-811b-9bd7c498f376)

**Comment by bschilder** [comment]
The analyses to get the most fetal-specific/adult-specific phenotypes, and the most fetal-specific/adult-specific cell types, are now encapsulated in a single MSTExplorer function (`run_congenital_enrichment`):
```R
results <- load_example_results()[ctd=="HumanCellLandscape"]
out <- run_congenital_enrichment(results=results)
```

**Comment by bschilder** [comment]
## Specific examples of foetal/adult cell type -biased phenotypes

Added a table showing specific phenotypes that are the most foetal cell type-biased (top) and adult cell type-biased (bottom). I think these make quite a bit of senses, since the foetal-biased phenotypes seem to be mostly morphological/developmental disorders, whereas the adult-biased seem to be related to aging.

![Screenshot 2024-08-21 at 11 08 08](https://github.com/user-attachments/assets/c18d7787-e727-43c2-bdcf-ba54d4b235de)
