### ISSUE TITLE
Consider adding figure explaining phenotype-cell type association testing

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/rare_disease_celltyping#76]
Mike Johnson suggested this during my viva. 

Could show two matrices (one of gene-phenotype associations and another of gene-celltype specificity). Then indicate that we're testing all combinations between the two matrices.

**Comment by bschilder** [comment]
Here's what I was able to come up with. Suggestions welcome @NathanSkene 

![study_design](https://github.com/user-attachments/assets/a564fbec-8bf3-4ef9-bac6-4db1f893abc4)

**Comment by NathanSkene** [comment]
Looks good, really helps to be able to show people the data structure. Incorporating a plot showing the regression would help, making clear what the axes are etc.

Remind me how the GenCC scores get converted to numbers? Could that be incorporated as well somehow?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bschilder** [comment]
@NathanSkene 
> Looks good, really helps to be able to show people the data structure. Incorporating a plot showing the regression would help, making clear what the axes are etc. 

Added scatter plots to demonstrate this.

> Remind me how the GenCC scores get converted to numbers? Could that be incorporated as well somehow? 

Added table with example GenCC scores to illustrate how evidence scores are used.

![study_design](https://github.com/user-attachments/assets/60be17a0-aeec-4250-b660-79db1f51df06)

**Comment by NathanSkene** [comment]
That’s perfect, thanks Brian, I think this really helps

From: Brian M. Schilder ***@***.***>
Date: Wednesday, 14 August 2024 at 14:41
To: neurogenomics/rare_disease_celltyping ***@***.***>
Cc: Skene, Nathan G ***@***.***>, Mention ***@***.***>
Subject: Re: [neurogenomics/rare_disease_celltyping] Consider adding figure explaining phenotype-cell type association testing (Issue #76)
This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



@NathanSkene<https://github.com/NathanSkene>

Looks good, really helps to be able to show people the data structure. Incorporating a plot showing the regression would help, making clear what the axes are etc.

Added scatter plots to demonstrate this.

Remind me how the GenCC scores get converted to numbers? Could that be incorporated as well somehow?

Added table with example GenCC scores to illustrate how evidence scores are used.

study_design.png (view on web)<https://github.com/user-attachments/assets/60be17a0-aeec-4250-b660-79db1f51df06>
