### ISSUE TITLE
How to plot a figure showing that most phenotypes associated with 'cardiac muscle cells' are associated with heart phenotypes

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/rare_disease_celltyping#8]
Plot fraction of the hits that are from 'abnormality of the heart' for cardiac muscle cells.

E.g. if the highest z-score is 25, and that is from that term, then fraction =1

**Comment by bschilder** [comment]
Figure 1:
https://github.com/neurogenomics/rare_disease_celltyping/blob/master/figures/manuscript_figures_july_2022.pdf
