### ISSUE TITLE
Try 'pruning' the terms associated with 'Pancreatic Stellate Cells'... if all leaf nodes of a parent are enriched, then drop the leaf terms. Then we can see a cleaner list of what phenotypes are associated with it

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/rare_disease_celltyping#9]
It's interesting because they have more phenotypes associated with them than any other cell type...

But they are not associated with 'abnormality of the pancreas' (though all other major classes of pancreatic cell type are associated)

Without pruning the phenotypes associated with it just look like a random mixed bag

**Comment by bschilder** [comment]
Took a somewhat inverted approach by checking if each term have an descendants. If it does, only include its most precise descendants. This helps remove redundant terms in the target prioritisation pipeline, while retaining maximum precision of phenoptypes.

```R
library(KGExplorer)
dat <- data.table::data.table(hpo_id=c("HP:0000001","HP:0000002","HP:0000003"),
                             name=c("term1","term2","term3"))
ont <- get_ontology("hp")
dat2 <- prune_ancestors(dat,ont=ont)
```
